name: Publish packages to NPM

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    name: Publish packages to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true
          scope: "@hex-labs"
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile
      - name: Publish eslint-config
        run: npm publish --access public
        working-directory: "./packages/eslint-config"
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish eslint-config-react
        run: npm publish --access public
        working-directory: "./packages/eslint-config-react"
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish commitlint-config
        run: npm publish --access public
        working-directory: "./packages/commitlint-config"
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish prettier-config
        run: npm publish --access public
        working-directory: "./packages/prettier-config"
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish stylelint-config
        run: npm publish --access public
        working-directory: "./packages/stylelint-config"
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish tsconfig
        run: npm publish --access public
        working-directory: "./packages/tsconfig"
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
