name: Publish packages to NPM

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    name: Publish packages to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile
      - name: Publish commitlint-config
        uses: pascalgn/npm-publish-action@1.3.7
        with:
          create_tag: "false"
          workspace: "./packages/commitlint-config/package.json"
          commit_pattern: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish eslint-config
        uses: pascalgn/npm-publish-action@1.3.7
        with:
          create_tag: "false"
          workspace: "./packages/eslint-config/package.json"
          commit_pattern: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish eslint-config-react
        uses: pascalgn/npm-publish-action@1.3.7
        with:
          create_tag: "false"
          workspace: "./packages/eslint-config-react/package.json"
          commit_pattern: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish prettier-config
        uses: pascalgn/npm-publish-action@1.3.7
        with:
          create_tag: "false"
          workspace: "./packages/prettier-config/package.json"
          commit_pattern: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish stylelint-config
        uses: pascalgn/npm-publish-action@1.3.7
        with:
          create_tag: "false"
          workspace: "./packages/stylelint-config/package.json"
          commit_pattern: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish tsconfig
        uses: pascalgn/npm-publish-action@1.3.7
        with:
          create_tag: "false"
          workspace: "./packages/tsconfig/package.json"
          commit_pattern: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
