name: Publish packages to NPM

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    name: Publish packages to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"
          always-auth: true
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile
      - name: Publish eslint-config
        run: yarn publish packages/eslint-config
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish eslint-config-react
        run: yarn publish packages/eslint-config-react
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish commitlint-config
        run: yarn publish packages/commitlint-config
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish prettier-config
        run: yarn publish packages/prettier-config
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish stylelint-config
        run: yarn publish packages/stylelint-config
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
      - name: Publish tsconfig
        run: yarn publish packages/tsconfig
        env:
          NPM_AUTH_TOKEN: ${{ SECRETS.NPM_AUTH_TOKEN }}
