name: Test Config

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile
      - name: Run test command
        run: yarn test
